### ISSUE TITLE
when the new mod chat will be available

### ISSUE THREAD

**Issue by katithy** [darknight1050/ChatUI#7]
Hi! first thank you for working on this! i have been looking for a long time for a mod to activate the chat in beat saber from oculus quest.

When do you think the new version of the mod will be available?

**Comment by NicolaiVdS** [comment]
hey @katithy,

sorry for the late reply due to current events i havent had time to spend a lot of time to work on the mod, this being said after the festive season is over i can fully concentrate agian on working the mod.

Kind regards
